@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Luan",
  "email": "luan1@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luan1@gmail.com",
  "password": "123456"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova Pergunta 1",
  "content": "Conteúdo da pergunta. 1"
}

###

# @name fetch-recent-questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
